/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package matise.mapbox;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.mapbox.mapboxsdk.maps.MapboxMap;


@Kroll.module(name="Mapbox", id="matise.mapbox")
public class MapboxModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "MapboxModule";
	private static final boolean DBG = TiConfig.LOGD;
	private static MapboxModule instance;
	private MapboxMap map;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public MapboxModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	public static MapboxModule getInstance() {
		if (instance == null) {
             instance = new MapboxModule();
        }
        return instance;
	}
}
